[package]
name = "res_errare"
version = "0.1.0"
authors = ["LambdAurora <aurora42lambda@gmail.com>"]
edition = "2018"

[dependencies]
gl = "0.14.0"
cgmath = "0.18.0"
glfw = "0.41.0"
memoffset = "0.6.3"
stb_image = "0.2.2"
tobj = "2.0.4"
